# Generated by Django 2.2.4 on 2020-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_num',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
