# Generated by Django 2.2.4 on 2020-01-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200104_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
