# Generated by Django 2.2.4 on 2019-10-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0002_auto_20191023_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='estate_type',
            field=models.IntegerField(choices=[(1, 'Flat'), (2, 'House'), (3, 'Plot')], default='Flat'),
        ),
    ]
