# Generated by Django 2.2.4 on 2019-10-29 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0003_auto_20191023_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='author',
            field=models.ForeignKey(on_delete='cascade', related_name='estates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='estate_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('House', 'House'), ('Plot', 'Plot')], default='Flat', max_length=8),
        ),
    ]
