# Generated by Django 2.2.4 on 2019-11-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0004_auto_20191029_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('property', models.ForeignKey(on_delete='cascade', related_name='images', to='estate_app.PropertyModel')),
            ],
        ),
    ]
