# Generated by Django 2.2.4 on 2019-11-12 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0005_imagesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesmodel',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate_app.PropertyModel'),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estates', to=settings.AUTH_USER_MODEL),
        ),
    ]
