# Generated by Django 2.2.4 on 2019-11-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0006_auto_20191112_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='image_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
