# Generated by Django 2.2.4 on 2019-11-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0007_imagesmodel_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesmodel',
            name='image_name',
        ),
    ]
