# Generated by Django 2.2.4 on 2020-01-03 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0008_remove_imagesmodel_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertymodel',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
