# Generated by Django 2.2.4 on 2020-01-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0010_usermessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
